Acceptance tests
kopo4eweb/qna pull request #4
Opened 2021-03-07 14:36 UTC by kopo4eweb

2021-03-14 12:49 UTC, vkurennov requested changes

2021-03-14 12:49 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    redirect_to questions_path, notice: "Question #{@question.title} delete."
если условие не выполнится, то сообщение будет не акутальным, тут хорошо бы разные сообщения возвращать, в зависмости от ситуации

2021-03-14 12:49 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    redirect_to question_path(@answer.question)
тут бы какое-то сообщение пользователю вернуть

2021-03-14 12:49 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +        expect(assigns(:answer)).to be_destroyed
лучше проверять изменение в базе через change

2021-03-14 12:49 UTC, vkurennov commented on spec/features/answer/delete_spec.rb
> +      click_on 'Delete answer'
перед удалением стоит проверить, что ответ есть на странице

2021-03-14 12:49 UTC, vkurennov commented on spec/features/question/delete_spec.rb
> +      click_on 'Delete question'
тут тоже надо перед удалением проверить, что ответ есть на странице

2021-03-14 12:49 UTC, vkurennov commented on spec/features/question/show_spec.rb
> +    expect(page).to have_content 'MyString'
тут нужно проверить список ответов, а не один ответ. и ответы должны быть разными

2021-03-14 12:49 UTC, vkurennov commented on spec/features/question/index_spec.rb
> +    expect(page).to have_content questions[1].title
т.к. вопросы одинаковые, то тест пройдет даже если будет выведен только первый вопрос, а не все. стоит сделать их разными, например, через sequence в фабриках

2021-03-14 12:49 UTC, vkurennov commented on spec/models/user_spec.rb
> +RSpec.describe User, type: :model do
где тесты на метод проверки автора? если ты пишешь какой-либо код, он должен быть покрыт тестами

2021-03-14 19:32 UTC, kopo4eweb commented on app/controllers/questions_controller.rb
> +    redirect_to questions_path, notice: "Question #{@question.title} delete."
fix

2021-03-14 19:39 UTC, kopo4eweb commented on app/controllers/answers_controller.rb
> +    redirect_to question_path(@answer.question)
fix

2021-03-14 19:48 UTC, kopo4eweb commented on spec/features/question/show_spec.rb
> +    expect(page).to have_content 'MyString'
fix

2021-03-14 19:57 UTC, kopo4eweb commented on spec/features/question/index_spec.rb
> +    expect(page).to have_content questions[1].title
fix

2021-03-14 20:01 UTC, kopo4eweb commented on spec/features/answer/delete_spec.rb
> +      click_on 'Delete answer'
fix

2021-03-14 20:29 UTC, kopo4eweb commented on spec/features/question/delete_spec.rb
> +      click_on 'Delete question'
fix

2021-03-15 08:47 UTC, kopo4eweb commented on spec/controllers/answers_controller_spec.rb
> +        expect(assigns(:answer)).to be_destroyed
fix

2021-03-15 09:03 UTC, kopo4eweb commented on spec/models/user_spec.rb
> +RSpec.describe User, type: :model do
fix

2021-03-15 10:00 UTC, vkurennov approved these changes

2021-03-15 10:00 UTC, vkurennov commented on spec/models/user_spec.rb
> +        question = create(:question, user: user)
используй let для задания нужных данных

2021-03-15 10:00 UTC, vkurennov commented on spec/models/user_spec.rb
> +    describe 'an answer' do
достаточно проверить только на одном (любом) типе объекта, метод-то универсальный

2021-03-15 10:29 UTC, kopo4eweb commented on spec/models/user_spec.rb
> +    describe 'an answer' do
fix

2021-03-15 10:35 UTC, kopo4eweb commented on spec/models/user_spec.rb
> +        question = create(:question, user: user)
fix

2021-03-15 10:40 UTC, merged